export const EN = {
    buttons: {
        ok: 'Ok',
        yes: 'Yes',
        no: 'No',
        confirm: 'Confirm',
        cancel: 'Cancel',
        add_account: 'Add Account',
        open_account: 'Open Account',
        new_account: 'New Account'
    },
    labels: {
        passphrase: 'Passphrase',
        cpass: 'Confirm passphrase',
        key_file: 'Key file',
        date: 'Date',
        time: 'Time',
        sender: 'Sender',
        receiver: 'Receiver',
        ammount: 'Ammount',
        fee: 'Fee',
        balance: 'Balance',
        hash: 'Hash',
        send_money: 'Send money',
        refresh: 'Refresh',
        send: 'Send',
        send_email: 'Send email',
        advanced: 'Advanced',
        gas: 'Gas',
    },
    app: {
        title_1: 'Triumf ',
        title_2: 'Coin',
        discription: 'Crypto currency application',
        network: 'Network'
    },
    tips: {
        add_account: ['Application generate new private key of chosen network, then transform this one to key file and upload to you.',
        ' Any data of this process will not stored on server side.'],
        open_account: ['']
    },
    err: {
        server_connection_error: 'Server connection error.',
        local_storage_rror: 'Local Storage error.',
        local_storage_read_write_error: 'Read/write Local Storage error.',
        wrong_account_params_object: 'Wrong account parameters object.',
        account_not_exists: 'Account not exists.',
        wrong_address: 'Wrong address.',
        wrong_passphrase: 'Wrong passphrase.',
        wrong_symbol: 'Wrong currency symbol.',
        bad_key: 'Bad private key.',
        bad_key_file: 'Bad key file.',
        bad_network: 'Unnoun network.',
        bad_transactions_object: 'Bad transactions object',
        wrong_account_params_object_field: 'Wrong account params object field.',
        eth_account_open_error: 'Ethereum account open error.',
        passphrase_cpass: 'Passphrase not equal confirmed passphrase.',
        passphrase_length: 'Passphrase should be at least 8 characters and less then 256 characters.',
        wrong_hash: 'Wrong hash.',
        wrong_receiver: 'Wrong receiver address.',
        wrong_ammount: 'Wrong ammount value.',
        wrong_gas: 'Wrong gas value.',
        raw_tx_error: 'Raw transaction error.',
        sending_transaction_error: 'Transaction not send. Please, try again.'
    },
    info: {
        account_opened_successfully: 'Account open successfully.',
        account_already_open: 'Account already open.',
        account_closed: 'Account closed.',
        account_already_closed: 'Account already closed.',
        account_created_successfully: 'Account created successfully.',
        open_create_account: 'Are You going to create new or unlock existen account?',
        input_passphrase_open_account: 'Please input your exist account passphrase.',
        input_passphrase_new_account: 'Please input passphrase to generate new account.',
        please_wait: 'Please wait...',
        fill_transaction_data: 'Please fill transaction data.',
        raw_transaction: 'Raw Transaction'
    },
    currencies: {
        ETH_name: 'Ethereum',
        ETH_symbol: 'ETH',
        BTC_name: 'Bitcoin',
        BTC_symbol: 'BTC',
        LTC_name: 'Litecoin',
        LTC_symbol: 'LTC',
        BTG_name: 'Bitcoin Gold',
        BTG_symbol: 'BTG',
        BCH_name: 'Bitcoin Cash',
        BCH_symbol: 'BCH'
    }
};
