export const RU = {
    buttons: {
        ok: 'Ok',
        yes: 'Да',
        no: 'Нет',
        confirm: 'Подтвердить',
        cancel: 'Отменить',
        add_account: 'Добавить аккаунт',
        open_account: 'Открыть аккаунт',
        new_account: 'Новый Аккаунт'
    },
    labels: {
        passphrase: 'Секретная фраза',
        cpass: 'Подтверждение секретной фразы',
        key_file: 'Ключ - файл',
        date: 'Дата',
        time: 'Время',
        sender: 'Отправитель',
        receiver: 'Получатель',
        ammount: 'Сумма',
        fee: 'Комиссия',
        balance: 'Баланс',
        hash: 'Хэш',
        id: 'Id',
        send_money: 'Отправить деньги',
        refresh: 'Обновить',
        send: 'Отправить',
        send_email: 'Отправить email',
        advanced: 'Расширенный',
        gas: 'Газ',
        change: 'Изменить адрес',
        status: 'Cтатус транзакции',
        block_height: 'Номер блока',
        timestamp: 'Время транзакции',
        from: 'Отправитель',
        to: 'Получатель',
        value: 'Сумма',
        gas_limit: 'Лимит газа',
        gas_used_by_txn: 'Использованный газ',
        gas_price: 'Цена газа',
        actual_tx_cost_fee: 'Стоимость транзакции/Комиссия',
        cumulative_gas_used: 'Кумулятивно использованный газ',
        nonce: 'Номер',
        input_data: 'Данные транзакции',
        size: 'Объём',
        transaction: 'Транзакция',
        summary: 'Содержание',
        details: 'Детали',
        feeRate: 'Цена комиссии',
        confirmations: 'Подтверждения',
        per: 'за'
    },
    app: {
        title_1: 'Триумф ',
        title_2: 'Коин',
        discription: 'Приложение для работы с криптовалютами',
        network: 'Сеть'
    },
    tips: {
        add_account: ['Приложение генерирует новый закрытый ключ выбранной сети,',
            ' затем преобразует этот файл в ключевой файл и загружает к нему.',
            ' Любые данные этого процесса не будут храниться на стороне сервера.'],
    },
    err: {
        server_connection_error: 'Ошибка соединения с сервером.',
        local_storage_error: 'Ошибка доступа к локальному хранилищу.',
        local_storage_read_write_error: 'Ошибка чтения/записи в локальном хранилище.',
        wrong_account_params_object: 'Wrong account parameters object.',
        account_not_exists: 'Account not exists.',
        wrong_address: 'Wrong address.',
        wrong_passphrase: 'Wrong passphrase.',
        wrong_symbol: 'Wrong currency symbol.',
        bad_key: 'Bad private key.',
        bad_key_file: 'Bad key file.',
        bad_transactions_object: 'Bad transactions object',
        bad_network: 'Unnoun network.',
        wrong_account_params_object_field: 'Wrong account params object field.',
        eth_account_open_error: 'Ethereum account open error.',
        passphrase_cpass: 'Секретная фраза должна совпадать с подтверждением.',
        passphrase_length: 'Сектретная фраза должна быть не меньше 8 символов и не более 256.',
        wrong_hash: 'Неправильный хэш.',
        wrong_id: 'Неправильный id.',
        wrong_receiver: 'Неправильный адрес получателя.',
        wrong_ammount: 'Неправильная сумма.',
        wrong_gas: 'Неправильная величина газа.',
        wrong_change: 'Неправильный адрес изменения.',
        sending_transaction_error: 'Транзакция не отправлена. Пожалуйста, попробуйте ещё раз.',
        tx_open_error: 'Ошибка открытия транзакции.'
    },
    info: {
        account_opened_successfully: 'Account open successfully.',
        account_already_open: 'Account already open.',
        account_closed: 'Account closed.',
        account_already_closed: 'Account already closed.',
        account_created_successfully: 'Account created successfully.',
        open_create_account: 'Вы собираетесь создать новый или открыть существующий аккаунт?',
        input_passphrase_open_account: 'Пожалуйста введите секретную фразу для разблокирования аккаунта.',
        input_passphrase_new_account: 'Пожалуйста введите секретную фразу для нового аккаунта.',
        please_wait: 'Пожалуйста подождите...',
        fill_transaction_data: 'Пожалуйста запоните данные для транзакции.',
        raw_transaction: 'Подготовленная транзакция.'
    },
    currencies: {
        ETH_name: 'Эфир',
        ETH_symbol: 'ETH',
        BTC_name: 'Биткоин',
        BTC_symbol: 'BTC',
        LTC_name: 'Лайткоин',
        LTC_symbol: 'LTC',
        BTG_name: 'Биткоин Голд',
        BTG_symbol: 'BTG',
        BCH_name: 'Биткоин Кэш',
        BCH_symbol: 'BCH'
    }
};
